"""The record of labels the user has cancelled.

A rejection is not a label and says nothing about the job: it records that one verdict
was wrong. Bulk runs are barred from reaching that verdict again, which turns a cancel
into evidence that ``docs/labeling-criteria.md`` still encodes the mistake.

Kept out of ``label_repo.py`` so that file stays under the 300-line limit, and because
the two have different lifetimes: labels are rewritten by every run, while rejections are
the user's own decisions and survive ``label-revert``.
"""

import sqlite3

# SQLite's default parameter limit is 999; chunk IN clauses well below it.
ID_CHUNK_SIZE = 500


class RejectionRepository:
    """Reads and writes the labels the user has cancelled."""

    def __init__(self, conn: sqlite3.Connection):
        self.conn = conn

    def record(
        self, job_id: int, label: str, source: str | None, reason: str | None,
    ) -> None:
        """Record that the user cancelled one label on one job.

        Append-only: cancelling the same label twice keeps both timestamps, because this
        is a record of when the user disagreed, not a set of flags.
        """
        self.conn.execute(
            "INSERT INTO label_rejections"
            " (scraped_job_id, rejected_label, label_source, label_reason)"
            " VALUES (?, ?, ?, ?)",
            (job_id, label, source, reason),
        )
        self.conn.commit()

    def labels_for(self, job_id: int) -> set[str]:
        """Return the labels the user has cancelled on one job."""
        rows = self.conn.execute(
            "SELECT DISTINCT rejected_label FROM label_rejections WHERE scraped_job_id = ?",
            (job_id,),
        ).fetchall()
        return {row["rejected_label"] for row in rows}

    def clear(self, job_id: int, label: str) -> int:
        """Drop the rejections of one label on one job.

        Called when the user applies that label by hand: they have changed their mind,
        and the old disagreement would otherwise block every future run.
        """
        cursor = self.conn.execute(
            "DELETE FROM label_rejections WHERE scraped_job_id = ? AND rejected_label = ?",
            (job_id, label),
        )
        self.conn.commit()
        return cursor.rowcount

    def labels_for_chunk(
        self, chunk: list[int], placeholders: str,
    ) -> dict[int, frozenset[str]]:
        """Return {job_id: cancelled labels} for one already-chunked list of ids.

        ``placeholders`` is generated by the caller from the chunk length; only those
        '?' marks are interpolated, and every id is bound.
        """
        rows = self.conn.execute(
            "SELECT scraped_job_id, rejected_label FROM label_rejections"
            f" WHERE scraped_job_id IN ({placeholders})",
            chunk,
        ).fetchall()
        grouped: dict[int, set[str]] = {}
        for row in rows:
            grouped.setdefault(row["scraped_job_id"], set()).add(row["rejected_label"])
        return {job_id: frozenset(labels) for job_id, labels in grouped.items()}
